services:
  npm:
    image: 'jc21/nginx-proxy-manager:2.14.0'
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    secrets:
      - db_password
      - db_user
    env_file: .env
    environment:
      DB_POSTGRES_HOST: 'npm-pgsql'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER__FILE: /run/secrets/db_user
      DB_POSTGRES_PASSWORD__FILE: /run/secrets/db_password
      LE_SERVER: 'https://stepca.homelab/acme/acme/directory'
    volumes:
      - /mnt/docker-data/networking/nginx-proxy-manager/npm:/data
      - /mnt/docker-data/networking/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - ./certs/root_ca.crt:/usr/local/share/ca-certificates/root_ca.crt
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - dockernet
    post_start:
      - command: update-ca-certificates
        user: root
    depends_on:
      npm-pgsql:
        condition: service_healthy

  npm-pgsql:
    image: postgres:17
    container_name: npm_pgsql
    restart: unless-stopped
    secrets:
      - db_password
      - db_user
    env_file: .env
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - /mnt/docker-data/networking/nginx-proxy-manager/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U npm -d npm" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - dockernet

networks:
  dockernet:
    external: true

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
