services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        export DB_POSTGRES_PASSWORD=$$(cat /run/secrets/npm_db_password)
        exec /init
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      TZ: 'America/Halifax'
      LE_SERVER: 'https://step-ca:9000/acme/acme/directory'
      DISABLE_IPV6: 'true'
      DB_POSTGRES_HOST: pgpool
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: npm
      DB_POSTGRES_NAME: npm
    volumes:
      - /mnt/docker-data/infra/nginx-proxy-manager/data:/data
      - /mnt/docker-data/infra/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /mnt/docker-data/infra/nginx-proxy-manager/custom-init/99-trust-ca.sh:/etc/cont-init.d/99-trust-ca.sh:ro
      - /mnt/docker-data/infra/step-ca/certs/root_ca.crt:/usr/local/share/ca-certificates/homelab-root-ca.crt:ro
    secrets:
      - npm_db_password
    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2m
    deploy:
      mode: global
      restart_policy:
        condition: any      
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - internet
      - databases_internal
      - media_internal

secrets:
  npm_db_password:
    external: true

networks:
  internet:
    driver: overlay
  databases_internal:
    external: true
  media_internal:
    driver: overlay
    internal: true
