services:
  mongodb:
    image: mongo:latest
    # container_name is ignored in Swarm mode
    command: --quiet --wiredTigerCacheSizeGB 0.25
    secrets:
      - db_password
      - db_user
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - /mnt/docker-data/databases/mongodb/data:/data/db
      - /mnt/docker-data/databases/mongodb/config:/data/configdb
    ports:
      - target: 27017
        published: 27017
        mode: ingress
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "localhost:27017/test", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - dockernet

networks:
  dockernet:
    external: true

secrets:
  db_password:
    external: true
  db_user:
    external: true
