services:
  mongodb:
    image: mongo:8
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    hostname: "mongodb-{{.Node.Hostname}}"
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        exec docker-entrypoint.sh mongod \
          --quiet \
          --replSet rs0 \
          --bind_ip_all \
          --wiredTigerCacheSizeGB 0.25 \
          --keyFile /srv/mongodb/keyfile
    secrets:
      - mongodb_password
      - mongodb_user
      - source: mongodb_keyfile
        target: /srv/mongodb/keyfile
        uid: "999"
        guid: "999"
        mode: 0o400
    environment:
      TZ: "America/Halifax"
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongodb_user"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongodb_password"
    volumes:
      - /opt/docker-data/databases/mongodb/data:/data/db
      - /opt/docker-data/databases/mongodb/config:/data/configdb
    ports:
      - target: 27017
        published: 27017
        mode: host
    healthcheck:
      test: >
        mongosh \
          --username "$$(cat /run/secrets/mongodb_user)" \
          --password "$$(cat /run/secrets/mongodb_password)" \
          --authenticationDatabase admin \
          --eval "db.adminCommand('ping').ok" \
          --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
    deploy:
      replicas: 3 # one replica per node
      placement:
        max_replicas_per_node: 1 # enforce one per node
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - internal

networks:
  internal:
    driver: overlay
    internal: true

secrets:
  mongodb_password:
    external: true
  mongodb_user:
    external: true
  mongodb_keyfile:
    external: true
