services:
  mongodb:
    image: mongo:7.0
    hostname: "mongodb-{{.Node.Hostname}}"
    entrypoint: [ "bash", "-c" ]
    command:
      - |
        cp /run/secrets/mongodb_keyfile /tmp/mongodb.key &&
        chown 999:999 /tmp/mongodb.key &&
        chmod 400 /tmp/mongodb.key &&
        exec docker-entrypoint.sh mongod \
          --quiet \
          --replSet rs0 \
          --bind_ip_all \
          --wiredTigerCacheSizeGB 0.25 \
          --keyFile /tmp/mongodb.key
    secrets:
      - mongodb_password
      - mongodb_user
      - mongodb_keyfile
    environment:
      TZ: "America/Halifax"
      MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongodb_user"
      MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongodb_password"
    volumes:
      - /opt/docker-data/databases/mongodb/data:/data/db
      - /opt/docker-data/databases/mongodb/config:/data/configdb
    ports:
      - target: 27017
        published: 27017
        mode: host
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 3 # one replica per node
      placement:
        max_replicas_per_node: 1 # enforce one per node
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - databases

networks:
  databases:
    driver: overlay
    attachable: true

secrets:
  mongodb_password:
    external: true
  mongodb_user:
    external: true
  mongodb_keyfile:
    external: true
