services:
  authelia:
    image: authelia/authelia:latest
    restart: always
    environment:
      - TZ=America/Halifax
      - X_AUTHELIA_CONFIG_FILTERS=template
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia_storage_encryption_key
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/run/secrets/authelia_db_password
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/run/secrets/authelia_oidc_hmac_secret
    volumes:
      - /mnt/docker-data/security/authelia/config:/config
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_key
      - authelia_db_password
      - authelia_oidc_hmac_secret
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - internal
      - databases_internal

secrets:
  authelia_jwt_secret:
    external: true
  authelia_session_secret:
    external: true
  authelia_storage_encryption_key:
    external: true
  authelia_db_password:
    external: true
  authelia_oidc_hmac_secret:
    external: true

networks:
  internal:
    driver: overlay
    internal: true
  databases_internal:
    external: true
