###############################################################
#                   Authelia Configuration                    #
###############################################################

theme: dark

server:
  address: 'tcp://0.0.0.0:9091/'

log:
  level: info

totp:
  issuer: Authelia Homelab

authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: auth.authelia.homelab
      policy: bypass
    - domain: "*.authelia.homelab"
      policy: one_factor

session:
  name: authelia_session
  expiration: 1h
  inactivity: 30m
  cookies:
    - domain: 'authelia.homelab'
      authelia_url: 'https://auth.authelia.homelab'
      default_redirection_url: 'https://redirect.authelia.homelab'

storage:
  postgres:
    address: 'tcp://pgpool:5432'
    database: authelia
    username: authelia

notifier:
  filesystem:
    filename: /config/emails.txt

identity_providers:
  oidc:
    jwks:
      - key: |
          -----BEGIN PRIVATE KEY-----
          YOUR KEY HERE
          -----END PRIVATE KEY-----
    clients:
      - client_id: outline
        client_name: Outline Wiki
        client_secret: 'YOUR KEY HERE'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://outline.homelab.lan/auth/oidc.callback
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signed_response_alg: none

      - client_id: komodo
        client_name: Komodo Core
        client_secret: 'YOUR KEY HERE'
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://komodo.homelab/auth/oidc/callback
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signed_response_alg: none
