services:
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo-core
    restart: unless-stopped
    ports:
      - "9120:9120"
    env_file: komodo.env
    volumes:
      - /mnt/docker-data/infra/komodo/keys:/config/keys
      - /mnt/docker-data/infra/komodo/backups:/backups
      - ./certs/authelia.crt:/usr/local/share/ca-certificates/authelia.crt:ro
    networks:
      - dockernet
    post_start:
      - command: update-ca-certificates
        user: root

networks:
  dockernet:
    external: true
