services:
  step-ca:
    image: smallstep/step-ca:latest
    ports:
      - "9000:9000"
    environment:
      - TZ=America/Halifax
      - DOCKER_STEPCA_INIT_NAME=Homelab CA
      - DOCKER_STEPCA_INIT_DNS_NAMES=step-ca,stepca.homelab,localhost
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME=step-ca
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_ROOT_FILE=/run/secrets/step_ca_root_ca_crt
      - DOCKER_STEPCA_INIT_KEY_FILE=/run/secrets/step_ca_root_ca_key
      - DOCKER_STEPCA_INIT_KEY_PASSWORD_FILE=/run/secrets/step_ca_password
    volumes:
      - /mnt/docker-data/infra/step-ca/certs:/home/step/certs
    secrets:
      - step_ca_password
      - step_ca_root_ca_key
      - step_ca_root_ca_crt
    networks:
      - infra
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    healthcheck:
      test: [ "CMD", "step", "ca", "health", "--ca-url", "https://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  infra:
    external: true

secrets:
  step_ca_password:
    external: true
  step_ca_root_ca_key:
    external: true
  step_ca_root_ca_crt:
    external: true
