services:
  step-ca:
    image: smallstep/step-ca:latest
    ports:
      - "9000:9000"
    volumes:
      - /mnt/docker-data/infra/step-ca:/home/step
    environment:
      - TZ=America/Halifax
      - DOCKER_STEPCA_INIT_NAME=Homelab CA
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,stepca.homelab
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME=stepca
      - DOCKER_STEPCA_INIT_PASSWORD_FILE=/run/secrets/step_ca_password
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
    secrets:
      - step_ca_password
    networks:
      - infra
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

networks:
  infra:
    driver: overlay

secrets:
  step_ca_password:
    external: true
