services:
  # --- Layer 1: The DCS (etcd) ---
  etcd:
    image: public.ecr.aws/bitnami/etcd:3
    hostname: etcd-{{.Node.Hostname}}
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd-{{.Node.Hostname}}
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-{{.Node.Hostname}}:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-{{.Node.Hostname}}:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-postgresql
      - ETCD_INITIAL_CLUSTER=etcd-vm-docker-adam=http://etcd-vm-docker-adam:2380,etcd-vm-docker-zeus=http://etcd-vm-docker-zeus:2380,etcd-vm-docker-bragi=http://etcd-vm-docker-bragi:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      databases:
        aliases:
          - etc-{{.Node.Hostname}}
    volumes:
      - /opt/docker-data/databases/etcd/data:/bitnami/etcd/data
    deploy:
      mode: global
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

networks:
  databases:
    external: true
