services:
  registry:
    image: registry:2
    environment:
      TZ: America/Halifax
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      # HTTP secret is used to sign state. Important if scaled.
      REGISTRY_HTTP_SECRET_FILE: /run/secrets/registry_http_secret
      # Support running behind reverse proxies
      REGISTRY_HTTP_RELATIVEURLS: 'true'
      # htpasswd basic authentication config
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: 'Homelab Registry Realm'
      REGISTRY_AUTH_HTPASSWD_PATH: /run/secrets/registry_htpasswd
    volumes:
      - /mnt/docker-data/infra/registry:/var/lib/registry
    secrets:
      - registry_http_secret
      - registry_htpasswd
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/v2/ 2>&1 | grep -qE '200 OK|401 Unauthorized'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != vm-docker-bragi
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - internet

networks:
  internet:
    driver: overlay

secrets:
  registry_http_secret:
    external: true
  registry_htpasswd:
    external: true
