services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    hostname: plex.homelab
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Halifax
      - VERSION=docker
      - ADVERTISE_IP=https://plex.homelab,http://plex.homelab
    volumes:
      - /mnt/docker-data/media/plex/config:/config
      - /mnt/pirateflix/media/tv:/tv
      - /mnt/pirateflix/media/movies:/movies
      - /mnt/pirateflix/media/animes:/animes
      - /mnt/pirateflix/plex/transcode:/transcode
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    secrets:
      - plex_claim
    networks:
      - infra_media-internal

networks:
  infra_media-internal:
    external: true

secrets:
  plex_claim:
    external: true

