services:
  # --- Wiki ---
  # It requires the outline.env configuration file
  # See: https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    volumes:
      - /mnt/docker-data/apps/outline/data:/var/lib/outline/data
      - /mnt/docker-data/apps/outline/certs/root_ca.crt:/opt/outline/ca-certificates/homelab-root-ca.crt:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/opt/outline/ca-certificates/homelab-root-ca.crt
      - NODE_ENV=production
      - URL=https://outline.homelab
      - PORT=3000
      - WEB_CONCURRENCY=2
      - SECRET_KEY_FILE=/run/secrets/outline_secret_key
      - UTILS_SECRET_FILE=/run/secrets/outline_utils_secret_key
      - DEFAULT_LANGUAGE=en_US
      - DATABASE_URL_FILE=/run/secrets/outline_database_url
      - PGSSLMODE=disable
      - REDIS_URL=redis://redis:6379
      - FILE_STORAGE=s3
      - AWS_ACCESS_KEY_ID=/run/secrets/minio_root_user
      - AWS_SECRET_ACCESS_KEY=/run/secrets/minio_root_password
      - AWS_REGION=us-east-1
      - AWS_S3_UPLOAD_BUCKET_URL=https://api.minio.homelab
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - OIDC_CLIENT_ID=outline
      - OIDC_CLIENT_SECRET_FILE=/run/secrets/outline_oidc_client_secret
      - OIDC_AUTH_URI=https://auth.authelia.homelab/api/oidc/authorization
      - OIDC_TOKEN_URI=https://auth.authelia.homelab/api/oidc/token
      - OIDC_USERINFO_URI=https://auth.authelia.homelab/api/oidc/userinfo
      - OIDC_USERNAME_CLAIM=preferred_username
      - OIDC_DISPLAY_NAME=Authelia
      - OIDC_SCOPES=openid offline_access profile email
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_REQUESTS=1000
      - RATE_LIMITER_DURATION_WINDOW=60
      - RATE_LIMITER_MULTIPLIER=1
      - ENABLE_UPDATES=true
      - DEBUG=https
      - LOG_LEVEL=debug
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != vm-docker-bragi      
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      - infra_internet
      - databases_internal
    secrets:
      - outline_secret_key
      - outline_utils_secret_key
      - outline_database_url
      - minio_root_user
      - minio_root_password
      - outline_oidc_client_secret

networks:
  infra_internet:
    external: true
  databases_internal:
    external: true

secrets:
  outline_secret_key:
    external: true
  outline_utils_secret_key:
    external: true
  outline_database_url:
    external: true
  minio_root_user:
    external: true
  minio_root_password:
    external: true
  outline_oidc_client_secret:
    external: true