services:
  # --- Wiki ---
  # It requires the outline.env configuration file
  # See: https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: always
    env_file: /mnt/docker-data/apps/outline/outline.env
    volumes:
      - /mnt/docker-data/apps/outline/data:/var/lib/outline/data
      - /mnt/docker-data/apps/outline/certs/root_ca.crt:/etc/ssl/certs/root_ca.crt:ro
    environment:
      - NODE_EXTRA_CA_CERTS=/etc/ssl/certs/root_ca.crt
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname != vm-docker-bragi      
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      - infra_internet
      - databases_internal
    secrets:
      - outline_secret_key
      - outline_utils_secret_key
      - outline_database_url
      - minio_root_user
      - minio_root_password
      - outline_oidc_client_secret

networks:
  infra_internet:
    external: true
  databases_internal:
    external: true

secrets:
  outline_secret_key:
    external: true
  outline_utils_secret_key:
    external: true
  outline_database_url:
    external: true
  minio_root_user:
    external: true
  minio_root_password:
    external: true
  outline_oidc_client_secret:
    external: true