services:
  komodo:
    image: ghcr.io/moghtech/komodo-core:2
    environment:
      TZ: America/Halifax
      KOMODO_DATABASE_URI_FILE: /run/secrets/komodo_db_uri
      KOMODO_HOST: https://komodo.homelab
      KOMODO_TITLE: Homelab Komodo
      KOMODO_LOCAL_AUTH: "true"
      KOMODO_DISABLE_CONFIRM_DIALOG: "false"
      KOMODO_PERIPHERY_PUBLIC_KEY: file:/config/keys/peripheries.pub
      KOMODO_WEBHOOK_SECRET_FILE: /run/secrets/komodo_webhook_secret
      KOMODO_JWT_SECRET_FILE: /run/secrets/komodo_jwt_secret
      KOMODO_FIRST_SERVER_NAME: "{{.Node.Hostname}}"
    secrets:
      - komodo_db_uri
      - komodo_webhook_secret
      - komodo_jwt_secret
    volumes:
      - /mnt/docker-data/infra/komodo/keys:/config/keys
      - /mnt/docker-data/infra/komodo/backups:/backups
    ports:
      - 9120:9120
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9120/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - databases_internal
      - infra

secrets:
  komodo_db_uri:
    external: true
  komodo_webhook_secret:
    external: true
  komodo_jwt_secret:
    external: true

networks:
  databases_internal:
    external: true
  infra:
    external: true
