services:
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo-core
    restart: unless-stopped
    ports:
      - "9120:9120"
    env_file: komodo.env
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - /mnt/docker-data/infra/komodo/keys:/config/keys
      - /mnt/docker-data/infra/komodo/backups:/backups
      - ./certs/homelab-root-ca.crt:/usr/local/share/ca-certificates/homelab-root-ca.crt:ro
    networks:
      - dockernet
    post_start:
      - command: update-ca-certificates && core
        user: root

  komodo-periphery:
    image: ghcr.io/moghtech/komodo-periphery:latest
    container_name: komodo-periphery
    init: true
    restart: unless-stopped
    env_file: komodo.env
    volumes:
      - /mnt/docker-data/infra/periphery/keys:/config/keys
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/proc
      - /etc/komodo:/etc/komodo
    networks:
      - dockernet
    depends_on:
      - komodo-core

networks:
  dockernet:
    external: true
