services:
  komodo-core:
    image: ghcr.io/moghtech/komodo-core:latest
    container_name: komodo-core
    restart: unless-stopped
    ports:
      - "9120:9120"
    env_file: komodo.env
    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - /mnt/docker-data/infra/komodo/keys:/config/keys
      - /mnt/docker-data/infra/komodo/backups:/backups
      - ./certs/homelab-root-ca.crt:/usr/local/share/ca-certificates/homelab-root-ca.crt:ro
    networks:
      - dockernet
    post_start:
      - command: update-ca-certificates && core
        user: root

networks:
  dockernet:
    external: true
