services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - TZ=America/Halifax
    restart: always
    secrets:
      - vaultwarden_db_password
      - vaultwarden_db_user
    entrypoint: >
      /bin/sh -c " export DATABASE_URL=postgresql://$$(cat /run/secrets/vaultwarden_db_user):$$(cat /run/secrets/vaultwarden_db_password)@pgpool:5432/vaultwarden && /vaultwarden"
    volumes:
      - /mnt/docker-data/security/vaultwarden:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - internal
      - databases_internal

networks:
  internal:
    driver: overlay
    internal: true
  databases_internal:
    external: true

secrets:
  vaultwarden_db_password:
    external: true
  vaultwarden_db_user:
    external: true