###############################################################
#                 Authelia Users Database                     #
###############################################################

# Use this file to define your users if you are using the 'file' authentication backend.
# Passwords must be hashed.
# You can generate a hash using: docker run authelia/authelia:latest authelia crypto hash ssha512 --password yourpassword

users:
  admin:
    displayname: "Administrator"
    password: "$6$rounds=500000$j9... (Omitted: Generate a real hash)"
    email: admin@homelab
    groups:
      - admins
      - dev
